### PR TITLE
Partition based formulation

### PR DESCRIPTION
**Pull request by fracek**
This PR adds partition based formulations for dense nodes. I marked it as draft because I will need to rename things after #33 is merged.

### CODE REVIEW

**Comment by jalving** [comment]
@fracek PR #33 has been merged. Let me know when this is ready for review.

**Comment by jalving** [comment]
@fracek PR #40 is merged. We can try re-running tests now.

**Review by jalving — APPROVED** [review]
Changes look good to me.

@fracek : are you still working on this? Once I get tests to pass, I can merge this.

**Comment by jalving** [comment]
One of the CI jobs failed because of a time-out. Some of the Cbc solves can take quite awhile. We can either continue to reduce neural network size, or we can probably get away with a longer notebook time-out.

**Comment by fracek** [comment]
Looks like now they're all passing.

**Pull request merged**
