### PR TITLE
Test notebooks

### PR DESCRIPTION
**Pull request by fracek**
Like we mentioned, this PR add testing of notebooks.

### CODE REVIEW

**Comment by fracek** [comment]
Looks like the issue now is that the GBT notebook uses gurobi. We should stick to cbc for all notebooks so that everyone can try them out and we can test them. What do you think?

**Comment by rmisener** [comment]
Agreed. @ThebTron, would you please switch to CBC in the black-box optimization notebook? Maybe try making the trees smaller in LightGBM if there is computational trouble with CBC.

**Comment by fracek** [comment]
The issue was that the second test run (the one testing notebooks) was overwriting the coverage from the main tests. I changed the notebook run to merge coverage with the main tests.

**Comment by rmisener** [comment]
In this pull request, import_network.ipynb still mixes ReLU and sigmoid activation functions. @fracek, possible to just make sure that the activation functions are ones we typically allow together?

**Comment by fracek** [comment]
I changed it to not use sigmoid anymore.

**Pull request merged**
